<?php

namespace ChrisReedIO\APIAmigo\Resources;

// use ChrisReedIO\APIAmigo\Resources\AmigoListenerResource\RelationManagers;
use ChrisReedIO\APIAmigo\Facades\APIAmigo;
use ChrisReedIO\APIAmigo\Models\AmigoListener;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Support\Str;
use Rawilk\FilamentPasswordInput\Password;

use function config;

class AmigoListenerResource extends Resource
{
    protected static ?string $model = AmigoListener::class;

    protected static ?string $navigationIcon = 'far-headphones-simple';

    protected static ?string $modelLabel = 'Listener';

    public static function getNavigationGroup(): ?string
    {
        return config('api-amigo.filament.navigation_group');
    }

    public static function form(Form $form): Form
    {
        return $form
            ->columns(4)
            ->schema([
                Forms\Components\TextInput::make('display_name')
                    ->required()
                    ->maxLength(255),

                Forms\Components\Select::make('integration_id')
                    ->relationship('integration', 'name')
                    ->required(),

                Password::make('webhook_secret')
                    ->label('Webhook Secret')
                    ->columnSpan(2)
                    ->helperText('Leave blank to disable signature verification, not recommended.')
                    ->copyable()
                    ->hidePasswordManagerIcons()
                    ->regeneratePassword()
                    ->generatePasswordUsing(fn() => Str::password(symbols: false))
                    ->maxLength(255),

                Forms\Components\Section::make('URL')
                    ->columns(3)
                    ->description(function (Forms\Get $get) {
                        $prefix = $get('url_prefix');
                        $event = $get('event');
                        $uniqueId = $get('unique_id') ?? '<AUTO-GENERATED-UNIQUE-ID>';

                        $parts = array_filter([
                            config('app.url'),
                            'api',
                            'webhooks',
                            $prefix,
                            $event,
                            $uniqueId,
                        ]);

                        return implode('/', $parts);
                    })
                    ->compact()
                    ->schema([
                        Forms\Components\TextInput::make('url_prefix')
                            ->live()
                            ->debounce(100)
                            ->alphaDash()
                            ->unique(ignoreRecord: true)
                            ->helperText('URL path segment to help identify the integration.')
                            ->rules(['lowercase'])
                            ->maxLength(255),

                        Forms\Components\TextInput::make('event')
                            ->helperText('Additional URL path segment to help identify the event.')
                            ->live()
                            ->debounce(100)
                            ->maxLength(255),

                        Forms\Components\TextInput::make('unique_id')
                            ->label('Webhook URL Listener Unique ID')
                            ->disabled()
                            // ->readOnlyOn(['edit'])
                            // ->disabledOn(['create'])
                            ->placeholder('AUTO-GENERATED-UNIQUE-ID')
                            ->default('Generated on save'),
                    ]),

                // Forms\Components\TextInput::make('handler')
                //     ->columnSpan(2)
                //     ->maxLength(255),

                Forms\Components\Select::make('handler')
                    ->columnSpan(2)
                    ->options(fn() => collect(APIAmigo::getWebhookHandlers())->mapWithKeys(fn($handler) => [$handler => $handler]))

                    // ->default('ChrisReedIO\APIAmigo\Listeners\AmigoListenerHandler')
                    ->required(),

                Forms\Components\ColorPicker::make('color')
                    ->columnSpan(2)
                    ->helperText('Leave blank to use the integration color.'),
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                // Tables\Columns\ColorColumn::make('color')
                //     ->label(''),

                Tables\Columns\TextColumn::make('display_name')
                    ->searchable()
                    // ->badge()
                    ->sortable(),

                Tables\Columns\TextColumn::make('integration.name')
                    ->label('Integration')
                    ->searchable()
                    ->sortable(),

                // Tables\Columns\TextColumn::make('url_prefix')
                //     ->label('URL Prefix')
                //     ->searchable()
                //     ->sortable(),
                //
                // Tables\Columns\TextColumn::make('event')
                //     ->searchable()
                //     ->sortable(),
                //
                // Tables\Columns\TextColumn::make('unique_id')
                //     ->searchable()
                //     ->sortable(),

                Tables\Columns\TextColumn::make('url_preview')
                    ->label('URL Preview')
                    ->searchable()
                    ->sortable()
                    ->getStateUsing(fn(AmigoListener $record) => implode('/', array_filter([
                        // config('app.url'),
                        'api',
                        'webhooks',
                        $record->url_prefix,
                        $record->event,
                        $record->unique_id,
                    ]))),

                Tables\Columns\TextColumn::make('handler')
                    ->searchable()
                    ->sortable(),

                Tables\Columns\TextColumn::make('created_at')
                    ->searchable()
                    ->sortable()
                    ->toggleable()
                    ->toggledHiddenByDefault(),
            ])
            ->filters([
                //
            ])
            ->actions([
                Tables\Actions\ViewAction::make(),
                Tables\Actions\EditAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => \ChrisReedIO\APIAmigo\Resources\AmigoListenerResource\Pages\ListAmigoListeners::route('/'),
            'create' => \ChrisReedIO\APIAmigo\Resources\AmigoListenerResource\Pages\CreateAmigoListener::route('/create'),
            'view' => \ChrisReedIO\APIAmigo\Resources\AmigoListenerResource\Pages\ViewAmigoListener::route('/{record}'),
            'edit' => \ChrisReedIO\APIAmigo\Resources\AmigoListenerResource\Pages\EditAmigoListener::route('/{record}/edit'),
        ];
    }
}
